### ISSUE TITLE
Varianten abbilden

### ISSUE THREAD

**Issue by davidhellmann** [martinherweg/craft-gonzo#14]
Halte ich noch mit für sehr wichtig.
`.button--red`

`.button--blue`

etc. Das man dann zwischen den Sachen switchen kann.

https://polaris.shopify.com/components/actions/button#navigation

**Comment by davidhellmann** [comment]
Keine Ahnung wie kompliziert das ist? :D

**Comment by martinherweg** [comment]
```"variants": [
    {
      "variantName": "divider Blue",
      "description": "divider Blue Notes",
      "opt": {
        
      }
    }
  ],```

**Comment by davidhellmann** [comment]
Ich muss dann mal noch das Design weiter machen

**Comment by davidhellmann** [comment]
Reicht erstmal. Polish dann später
