### ISSUE TITLE
Verhalten beim ersten Aufruf

### ISSUE THREAD

**Issue by davidhellmann** [martinherweg/craft-gonzo#30]
Beim ersten Aufruf `/patternlib` sollte das erste Modul vom ersten Folder standardmäßig geöffnet sein.

**Comment by martinherweg** [comment]
Was hältst du davon eine kleine Landingpage vorzuschalten? Text evtl. konfigurierbar via config. Oder alternativ ne langingpage.html in `templates/patternlib` erstellen die dort gesetzt wird.

**Comment by davidhellmann** [comment]
So art Onboarding?

**Comment by davidhellmann** [comment]
Ich close das hier. Ne kleine Welcome Page muss rein!
