### ISSUE TITLE
Module Excluden in der Navi

### ISSUE THREAD

**Issue by davidhellmann** [martinherweg/craft-gonzo#53]
Es wäre schön wenn man Module aus der Navi Links raus nehmen könnte. Würde es über den Status machen "hidden". 

Was denkst? Oder eigene Config option: `visible => true` als default und halt false. Ist wohl sogar noch sauberer da wir den Status dann nicht missbrauchen.

**Comment by martinherweg** [comment]
Denke config options ist das einfachste und sauberste.

**Comment by davidhellmann** [comment]
Sieht gut aus!
